name: Release

on:
  push:
    tags:
      - "v*"

env:
  GOLANG_VERSION: 1.19.1

jobs:
  release:
    name: Release & Sign
    runs-on: ubuntu-22.04
    env:
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@cc23fe1cf04164ea4c208611cf647a013c6f8cc5
        with:
          cosign-release: 'v1.12.1'

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@d94f46e13c6c62f59525ac9a1e147a99dc0b9bf5 # v0.17.0

      - name: Install signing key
        run: |
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6
        with:
          version: v1.9.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}

      - name: Cleanup signing keys
        if: ${{ always() }}
        run: rm -f cosign.key || true
