name: Release

on:
  push:
    tags:
      - "v*"

env:
  GOLANG_VERSION: 1.19.1

jobs:
  release:
    name: Release & Sign
    runs-on: ubuntu-20.04
    env:
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@162dfdf7b9ab8be88c95b4fc982792c4c273e27a
        with:
          cosign-release: 'v1.12.1'

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@9fece9e20048ca9590af301449208b2b8861333b # v0.15.9

      - name: Install signing key
        run: |
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # tag=v3
        with:
          version: v1.9.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}

      - name: Cleanup signing keys
        if: ${{ always() }}
        run: rm -f cosign.key || true
